// <auto-generated />
namespace ProjektASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration13));
        
        string IMigrationMetadata.Id
        {
            get { return "202401282011520_migration13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
